linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - bodyclose
    - depguard
    - misspell
    - unconvert
    - gocyclo
    - dupl

linters-settings:
  gocyclo:
    min-complexity: 40  # Increased to allow some complex handlers
  dupl:
    threshold: 250  # Increased to allow similar test cases
  depguard:
    rules:
      Main:
        allow:
          - $gostd
          - github.com/google/uuid
          - github.com/shopspring/decimal
          - github.com/SahithiKokkula/backend-2-cent-ventures
          - github.com/stretchr/testify
          - github.com/lib/pq
          - github.com/gorilla/mux
          - github.com/gorilla/websocket
          - github.com/prometheus/client_golang
          - github.com/redis/go-redis
          - github.com/sirupsen/logrus
          - github.com/go-redis/redis/v8
          - github.com/google/btree

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - docs  # Skip docs folder to avoid package mixing issues
  exclude-rules:
    - path: _test\.go  # Disable dupl for test files
      linters:
        - dupl

run:
  timeout: 5m
  tests: true
